#!/bin/sh

# Run the development server, serving locally on port 5000.
#
# This will listen on 127.0.0.1 only; to listen on all interfaces, use:
# flask run --host=0.0.0.0

export FLASK_APP=paranuara.paranuara
exec flask run
